apiVersion: v1
kind: Secret
metadata:
    name: renovate-secrets
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:S5jgXO0wrht73Lf28qSMII5/q4Kpq1Ch6u/UGlgYyBSAhmxUwasc8A==,iv:b5Qv9c7rdlk5fFvQawKvhAVOdM5a9H2G26DsKRF4D/E=,tag:EWUw6Fv5hpkLkfdCAB57hw==,type:str]
sops:
    age:
        - recipient: age1nx88s3q0e02zhyycd9q4lwxqts9e6cenrvlxfp7ka2ghaxzwa5hqhex8h6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RXZINlNublo5K3ViOVVk
            U2t5ZGdZMWhRS1pIb1JRZ3hWRE1pNzVTU0I4ClBKT1dYaUpsVDcyUWtEMmJYVFY4
            RXJaSVRaQzdBQzNqVzU3MzFJQUpYOFUKLS0tIHdGMzk3eHVjUFdvL3k5ZmU0TVpF
            djllMktsSVE3eUd4Yitob0lBeEo4QUEKq9Ntj9fYv8E8VVgvPT4EDT57iwi1zleq
            M0ZrJqVSX67DK89VCRgz6+IX0U7Xk0gfxMXp56T1TZv2PHA5xGYdBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T15:37:36Z"
    mac: ENC[AES256_GCM,data:Da9C5/o2gDvIEog8+KussfHXSv5WWY88Z5ZrfTAdZgGeiogSZA172aTyT3XRnzxrrCke+C+xEBw+4KS9SbfDVPn3UzhFYNuCRnkk073O8nivkPYdlWHWWU54CFtfgZtamgGbKvKvdUgKPXZoxCgx2LYPTLWBRUTV1awicH8x13g=,iv:9CsC2jju1Ree/NneKmnDyOE03DvUZyeLundn+xf5WmA=,tag:BLXxKi4v5CmzDHFehwZR3g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
