apiVersion: v1
kind: Secret
metadata:
    name: renovate-secrets
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:lqxq/NCa1/yIu/2VgI9qQsTfNZcxg3ASFZRQy0elDbRAjttSYiY7Ow==,iv:e48AHlPTiHhsYXctN9J0JJsFjwGGe8x7IsacCGMxFtA=,tag:dcg0AWM2uax5HiIIE+z9rA==,type:str]
sops:
    age:
        - recipient: age1nx88s3q0e02zhyycd9q4lwxqts9e6cenrvlxfp7ka2ghaxzwa5hqhex8h6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVHl2Z2tTU3hQTmJKVWIy
            Q0trTE5sRDFyam56UFdXSjh6bTJQQXB0UDJ3CnRyRGVDbjc5NVFEMGpyMFhIRUVa
            Y21WeUtCRGhoQjRrR2h6NWJySVA4QzAKLS0tIEdHNndTZTRFa0NOYkFYM3pBUFBw
            cjM1NkZjYU0yYUdsVXVsQWlHbU4ybTgKGIAzDIbjaV/NyRK2wttakXXX9jYoJ7/k
            lVieYdFmz7sdmK7PC2Euz6KMydQqAfB7+VZOhNxY7ujF4lKhUvcy9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T15:43:50Z"
    mac: ENC[AES256_GCM,data:mYOy2BwlPbS0LBuOX2hHBq+TvuhsAK/XZt7B+AWyWY1l3GAWu5B8Jdo3qkcghTMIO4k7urqUeHd0o4on/ffzxgUuV/Ctpl+tBfV8gVs5mWAdLfJTGXw+kJRmgMqH5epawsKWqwsuGJ9H5uH4VRSlT7l2faUVHIvjOhNGRNrHpFU=,iv:moWS6s+Cv4wOJFEJE8e1fGmIu05nIzgqG8MXgCbLXdQ=,tag:uIfbPVWPo/GK1Pa+hfNvRg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
