apiVersion: v1
kind: Secret
metadata:
    name: renovate-secrets
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:u1bw+Qs1Q7/63YCiyUfJvbW3T8f0n0qE7cl/MhGVVNy9uIqd1dCpuI0n9ZYWv6LERrDoM70NpYyzvWX8MP0=,iv:jx3ivQMiO2/06ZABKkPs7ugxMOTCJuFZTVeGkCpDsHY=,tag:LoBgQe2xn8T2J1zGivZJDw==,type:str]
sops:
    age:
        - recipient: age1nx88s3q0e02zhyycd9q4lwxqts9e6cenrvlxfp7ka2ghaxzwa5hqhex8h6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RXZINlNublo5K3ViOVVk
            U2t5ZGdZMWhRS1pIb1JRZ3hWRE1pNzVTU0I4ClBKT1dYaUpsVDcyUWtEMmJYVFY4
            RXJaSVRaQzdBQzNqVzU3MzFJQUpYOFUKLS0tIHdGMzk3eHVjUFdvL3k5ZmU0TVpF
            djllMktsSVE3eUd4Yitob0lBeEo4QUEKq9Ntj9fYv8E8VVgvPT4EDT57iwi1zleq
            M0ZrJqVSX67DK89VCRgz6+IX0U7Xk0gfxMXp56T1TZv2PHA5xGYdBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T14:55:59Z"
    mac: ENC[AES256_GCM,data:uZvRQx5QHJ/3X2i2JESEcXxEInj3IlTKvUtCsIjFoatrMuLiC7rwXKjpRe5hFhTIq6DHCtemlDP/DvV4O0E/tCK42lsACp98VpKqH5jExB2c4VDyj/GoDpI4KzPde9S5ioENUvKrFiiqo75OY3gMo4LnpyHw/IPR4wBUtSyxtMY=,iv:lDmbLJEbmvUryUZJRfL3rz0fJy1F7frhBBKr6M4WuXw=,tag:v4Ak2shPbTixxyw+3/ASbg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
