apiVersion: v1
kind: Secret
metadata:
    name: longhorn-b2-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:fqTXGGHcs1pqYg==,iv:2hVP7gyo8Bm6e+qQMshKq574N114HZKJuaVpVAMmt3w=,tag:wKjMrGOlvzPLXN4IxIdo5g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:FlBt4/sN7d25Fw==,iv:mMHNdFG3G04NEXyOUsDahmju/dX+vO3+r+KAouiWncM=,tag:xoAjBgy/4SYEnMZ8/Qvgqg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:oUvvgMvd+r3SS7QzD3Mf4qVXqIHuLQlvAQ==,iv:WFx7UnYnvU7DzK5shI1ps+ylEnGleFkdz6cyenujDjc=,tag:Je+qJ0yyW3RDqYWmCjQrxg==,type:str]
sops:
    age:
        - recipient: age1nx88s3q0e02zhyycd9q4lwxqts9e6cenrvlxfp7ka2ghaxzwa5hqhex8h6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJeFphMGtGUEg4Y2xIT0o0
            eFY3aEV4VDNscUJyN0tJblJYalp4TlJrNkZNCkcrcmhVTk5LRW15UnVjNmx4bTg4
            R1NtR1lkV0xseU1HdjMrWDU0b1BLYlkKLS0tIGRXNjUrVGF5ZDVaSTBDVUxJMmg5
            dTlvUzg5bkpFZUd4ZWZFMXhBaThPWk0KGP9NLXBNI24RA83r2Hdb0hM9DqmrpAjc
            2p8qnc0so7+znL0JOa6bMqglwOdlSqLcERTTwpPXKm8krVfsveuYrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T00:13:28Z"
    mac: ENC[AES256_GCM,data:7MtLwwCKtTGVss8KtEm6o4jjCzkrcE8KabFoMJrraUM/B62AZ6h9sxvoC6LchSHlivdcbeFcgap5+NlhCkOPOYK4ft9qeAzMo0+XrWSEcXzRmyh9+gipNFXabx9KX50EgnIxmv+Sr0UbjEt555LOm3eji8DhkBycgHc+/kdVxTk=,iv:9B1pR4CbBUD4hopPl5YPpZITdipiQZuAiKHgnEoj+qs=,tag:Kyq09AWcxRqgosc0W9YBog==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
