apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: daily-backup-b2
  namespace: longhorn-system
spec:
  cron: "0 6 * * *"
  task: backup
  retain: 7
  concurrency: 1
  groups:
    - backup-b2
