apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  values:
    defaultSettings:
      defaultReplicaCount: 2
      defaultDataPath: /var/lib/longhorn
      backupTarget: s3://longhorn-backups@192.168.2.171:9000/
      backupTargetCredentialSecret: longhorn-b2-secret
    persistence:
      defaultClass: true
      defaultFsType: ext4
    ingress:
      enabled: false
