apiVersion: v1
clusters:
- cluster:
    server: https://35.180.68.71:6443
    insecure-skip-tls-verify: true
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrRENDQVRlZ0F3SUJBZ0lJUXBvODlnbnJrOHN3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOelE0TlRVME1ESXdNQjRYRFRJMU1EVXlPVEl4TWpjd01Gb1hEVEkyTURVeQpPVEl4TWpjd01Gb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJIUDV0N1pIZm1YazFLU3MKanpvUU9veEFZN0xVNmYxRlpNVFV0c2RCQnFoMGtEdGdwNElkNDg5ZHNXS0hZLy9qeVp3ZkF6REJxVEFTcXNUSgpMSEJsc1lHalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUk4yZUlXdW5IOEEzRGg4cGZFTThjOUxlS2gvekFLQmdncWhrak9QUVFEQWdOSEFEQkUKQWlBMXl5TklBNGdibEljcVJRakZLOTJOODNvVFVvVFg4cEZlYlNUeGhqeGtwQUlnWkpCaVJkQWRvTnN1Sk0vagpmRVZMVVR1bkdPQnptWFNPWmhra0ExeXRWamc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzTkRnMU5UUXdNakF3SGhjTk1qVXdOVEk1TWpFeU56QXdXaGNOTXpVd05USTNNakV5TnpBdwpXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzTkRnMU5UUXdNakF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTMyszMFFKUzQ2WGt4ZXVab3dScmFIY0R0L2RoNXRmdzQ0VVNiM0JRL3IKZEsyMUNsVi9aS2NDVFpVYjlrazJZOVZWYVo1aEQyNUlvc0h6ZCt2ZFdFSVNvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVRkbmlGcnB4L0FOdzRmS1h4RFBIClBTM2lvZjh3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQU8vSVZXbVJFN0tqNFo2ZXhVeERYSWlBRkQyUnBBWVkKbGY2UXFtSDBkYmJqQWlFQXBRZWpYYzBOWWJIUGhxS3hmVUo1eVZJTHlqN1ZYM3RFYzl4QzVUNy84VXc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUxJeUNFUXBESHo3cVlOQXowTDFmUDl0V0pUVVdOeXE5T3BvK1dtcVM2OWpvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFYy9tM3RrZCtaZVRVcEt5UE9oQTZqRUJqc3RUcC9VVmt4TlMyeDBFR3FIU1FPMkNuZ2gzagp6MTJ4WW9kai8rUEpuQjhETU1HcE1CS3F4TWtzY0dXeGdRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
