apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:jGccIV78WbgQgt76JFexapAjP099MzY1By+f+GSYw1KZAHuDZIn8GDVnLYUJtN1grcUYIG00lN0iAOiG+/Sd216JnA+SVEMIvvYyUR9HV8H5SZySmLKTkj9c2aVizcs/Z+HXPsje9G5agbMiGUb98nN0jPn+UkSeUJFIAA==,iv:PakbdAE+mvHzlEFhDo2YmbyZn8DRq+roBCjkhLErfk8=,tag:0/VsFZWv9zxmohihb8/GZA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: renovate-container-env
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfmusxgxpv8292s3d2x60lemqscsff7zcsnfxd67nk348pzlgs3qth3q8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWk83K1hEVTB5TXFLd2Jp
            L3B6VmtoRWFPODBFS2hmR045RlBWaWJzUmd3CmZNbEpvTVNDREpyNnNKNXMyUFhO
            aFM3eVhjM3FMTWhFb0E5RjFralBpSEkKLS0tIGZIbkNwU2xZWTh5VEttL0hPMGJu
            NHVibi9hTnBJT0I1b2JtZC9QL2Zjc1EKkGREwARmCQ3NQu9JiE119R7Yhksw1pEH
            TNX86GVwLVHVDPZV3EGxruN5vLk0EvlZgIJkDuihIafyWpMFLKDUag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-25T14:55:10Z"
    mac: ENC[AES256_GCM,data:eBPrGIZUCaVhAS31I2p2D+gmqkhbMbaf22Rf9ykKZtJYiO7r2YZabQE/IZCxo1db/lRRtb98kvf58XNNilkw8DNvTH66pIsnh//lN2J4r6Ix4NpF9PYugLnVGkwQbgcIB5jDhfzht9Hd0se5brvH1GmCENLZON3g8AT8O0Phh5o=,iv:isA+4YlqcP1xTdQCcWggylo3lmstSTs7VRclli5Abdg=,tag:0ApxijO7I51FGuYQeZ6g2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
