apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - helmrepository-prometheus-community.yaml
  - helmrepository-grafana.yaml
  - helmrepository-victoriametrics.yaml
  - helmrelease-victoriametrics.yaml
  - helmrelease-grafana.yaml
  - helmrelease-node-exporter.yaml
  - helmrelease-kube-state-metrics.yaml
  - grafana-storage.yaml
