apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
    namespace: forgejo-runner
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:WwZFSyKuuqt4vXiTrki/OaIewMV3Ya1vc2skU1ARY9K33+/WbDDEo89pXg==,iv:ATLfwYg5v016NPNeO5jZILVmwHBq4dY14tw5L9cvtTY=,tag:5+j7al8SsGmNFEkojl85fg==,type:str]
sops:
    age:
        - recipient: age1nx88s3q0e02zhyycd9q4lwxqts9e6cenrvlxfp7ka2ghaxzwa5hqhex8h6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZldzZnRtZ21MZThoQTJT
            UU5kYncxRnlaUlZrNGJhaVlqZUs5VGxCRjJvCnNnSVpKSGVaaTBCWXF1Vi9xc05l
            N0FMelVUb2ZvWEtZOU9uMzYrQUQ2Q1kKLS0tIG5nbksyY2hMOGRTRGV1Y1lzTGc4
            OWVrRDJ3VnBTektlc1R6WXExR055bHMK2GYr2G1kIXp6nuikUAiZa+AAWReY2J6X
            OEqOkpRch6OujXq7blsbIzkipx3TS3X9lmT96f+OCLuMxGJ+/2UhWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-28T00:09:39Z"
    mac: ENC[AES256_GCM,data:Hoy0usd+9EMM2cC5k3mFCT0VBFj+IB6V4C/Q0iXfWd2xp+7i/gs58Lbj5pPwyqGNRw7OApualsMVJDAHkV2eKjxacqMgpO2DjOwOR9swfpgCyMMYc2P9Rg4pNcG9WDMNZWNUCv8xM1YEmzlr0viBHn5/FfFT/sxaAkgx8T/DLHs=,iv:D4i/VB3yv2W8O5sw2uA9/71Z+ejP4PS2YXCjKwjMUik=,tag:9DfdO9WejL6ewhIaMnS0cA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
