apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:lb4+uI60b7Kxrm4otSa8RoexnERa/yCs7FKpzG25iiGgTV4nZtiUhqAamUDQPrDw/fC4jiQKFqAulblyZloNSnWRInWCxG8HSsHbky7WWVmmBmia+dxSD/srBH1j+h6W+tOCp8QYFMBzaNObGwFahGQNG1lafN1Ft9qpw4Dbzhi1LCan6sDm3zOy5gwhuUdgVJUe/P06jp7jZQ2AkS3d87ov2U85N1++VeGApqXxhKsYfvkwaYUmglKQklzE/YZUI4rbNt3YZUzSRFJOw+4//hTt5kam9LUO1LRHYyCtSrub2OtFXJ4upNTUp6E=,iv:v4Ero4qJUbatXIN630nQpUCdvi0UaY+/FUgUqsAAPWQ=,tag:b1p+XC+xN8SAKqEEttCgIg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfmusxgxpv8292s3d2x60lemqscsff7zcsnfxd67nk348pzlgs3qth3q8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvK3NIVmdoNU9MY1U3ckor
            dXRMQlZCOGFFT3UrSXhRRHc0aUJncGNKcmc4CklhRGV2bEdNZWZJNGt0UzBST3Vl
            T093VHk1RDU3dEgzUXlELzZUUmtONTAKLS0tIGl2Y2tPYWJSTGIwTTJ4ejFBaFNM
            ZndWdzJrSk02OEtoQytPQTR5dXJvWE0KolJvcyyRxuHrlgG1h82tkZ65A2iLGEUy
            jCqPM8cYROck8QY2Zz2DBSJiPlBK1SapWOIDD8idgd7TD4CDa1pCYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-11T13:26:50Z"
    mac: ENC[AES256_GCM,data:ZQSG8vO082EKEIZGJgAffj7DjAvyLQ3ZvOA4GQU8uCY8ajUI35N+njCtssuVCxb+3Ah4ImvPbaSTU1JYv+YEom0lwiUqpnC5+0bm91buKMrq2VmSYXeHkLgtKzY2ngJf1dLKBZWs9COjX3hCcU4c9MbAocmxNUx4XERQvImZj24=,iv:3/X+q+H/InD4QppSFm/qiMs2k4lK8txNicy4iQp6AcQ=,tag:ZsbGxzsdHmQjEHEAYoylYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.8.1
