apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-env
    namespace: pgadmin
type: Opaque
stringData:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:g6x3K8Ggbo4W+EgzhH5ziybac0h+UQj3Eg==,iv:JtompUEa2KIaQoaPoX+fQWRfnpWV8cONiLCWTUzVRzY=,tag:6bhd8in8PDJvhustiaTqSQ==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:zOlxLjpuGGuln2vmKr453vZoweUD1uC+v5HyBY7KcAc=,iv:GLwGCpPJD0AuDyfQol3PBAMuW+/qUExCT0xyUINfoIo=,tag:JPJyYRQ/HVTqv4TLulo6rw==,type:str]
sops:
    age:
        - recipient: age1nx88s3q0e02zhyycd9q4lwxqts9e6cenrvlxfp7ka2ghaxzwa5hqhex8h6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyK3J3Wi9QODMrV3hMTWlI
            eUNNSm84U2hnb0FKd3Q3Y21oelNTaWl1cGxNCkppaHNDZ3g3ZGtkcGUvN3RQU2hl
            U1liTFJoSDkrTS9uN04xSjRzcmhvZGMKLS0tIHBSNjNNZ0NwRUVOSUZiRzJRcmpP
            MWh3cEZjaSs3emdRSkE2OHNWb0RMdGcKKQ0ooqEgsrO4HebvLaHQ21yfMI0pF+b2
            mNU66LgF++TsxsjJdqyE1jb4iD+v+NbTmIEIHqCtf/s+jJ8a5fgvDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T19:50:33Z"
    mac: ENC[AES256_GCM,data:XXi8eup2Xh9adaRYjpTqKvj4T66srTVs8f+XdWy26Bm7DRueJp/emkvMZsa/2I3r/Py92Ub0caLD2gHjCiFxkm8mM8vq60WKJTvvhWqi9zrL78QHqcM64HQEO7qrLGi4gCcUXkQEl5Qiwt8CMPisHb4GcKNyS8bBLFoIt1n50VA=,iv:hFUzKvU0ExDr05fgXNyaiaYrh9zZF83EcMuo+ofRC24=,tag:IoPkyp1WLmQqw3ydIqGEEg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
