apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-s3
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:UO2f6QzdBich+d0d+fvr6d52FttZRNAnIM6MRFbEHzo=,iv:tr03o7xybg112RgCQbR/3n1fR4hRcLe5giCE+jf/IUg=,tag:l8HlfIGwAwdKLutP66ymFA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:3JW/PlwMANiM9Etvy2+UdJhKFamVfN0JJk2aymoefBTilgQhTqqg7BuslNEHYOBrwKnbwUynLMo7xVcf8t7lYg==,iv:3d1e2ZiMkC5S7qB0Sp4fqkfsNNInWTLfTzbLe24L9Os=,tag:PHLLkVeASQ42iIFdFtVxTA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:ZpsvRjuwl3VgU4KBoIvUoun0xNT5Pa051XVFEyR+sOgOKUEviV8jdxZRE30pUefgXq5BZVT0KEPmNefty9x5GXc=,iv:iEBiolrdISfpNHWaZu7xmA0KdJ50ZXKPHNgDZHkZzOU=,tag:Nn1xwTw4OcYoUTHof1MKDg==,type:str]
sops:
    age:
        - recipient: age1nx88s3q0e02zhyycd9q4lwxqts9e6cenrvlxfp7ka2ghaxzwa5hqhex8h6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1REdVZWt0SnpPYjFUc3cz
            emFjWUo1bjRpVCtPUms0TkNqYWFBMjZ3aVgwCjVlTUJrMkNrRitGdHZDUVE4K3ZE
            NFYzZFFTcDl2elN5VjNjOXQya3V4MWsKLS0tIHNhU21vWm1YY2R0cTZHT1lBbys0
            eERiNTJndzNaa1AvL01DYnhrMjhHZmcK5o/ERNYhFWuOb/P/od3nKpATq1rANy0+
            +ivvOjdiiosc19cHMMsUFSc9eqqcDX3ipGa8j6U/Jo1duvUozMvZEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-19T19:34:39Z"
    mac: ENC[AES256_GCM,data:B4dQ3H3hUfXuZU7WTXbmkVN/3UCAPR1N7UD/SBUgVjVEGQ48Z5d9sVsXW6OkKccXJ9l5IPuaCbgrD1rNyj4bkwXhIex0vpe8B5druyP3wbx/peWllutaIX6X+RX3mapT8eGZMRtYnPOSxdZxFGYqsysVmL8ajvtK51xDU0ZeJY0=,iv:ZJ4n4BX5jvTE9AKc5UdX/cvfHyc0q646OtQt1qsEqr0=,tag:eRULQlsxzllaVg5q/Ko2Bw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
