apiVersion: v1
kind: Secret
metadata:
    name: velero-backup-s3
    namespace: velero
stringData:
    cloud: ENC[AES256_GCM,data:ZVrkxK/KxNOZ2eJjauMRBbFXJXvrjoj8NVGS330Rh16veoegot/E//HxkpCrfzVQI9Uphby4Zz2sduykikILwaTJZwfYPhXYLBWhMo7s8aKT7AEWjxJBWZnw//nATSj578l6gj7HdYNCKefOhpMkIcZ0W9OzELhoHHp6g30GSgqZmqKHyaKP0JNG07xCxu9iwPU51A==,iv:NzYzkKIACmdIubAesJFE4p++T+K1NBg7MrCP3tpesJk=,tag:b2u5Nx8wyqPvglcGr5zaxQ==,type:str]
sops:
    age:
        - recipient: age1nx88s3q0e02zhyycd9q4lwxqts9e6cenrvlxfp7ka2ghaxzwa5hqhex8h6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUUdaTVBZOXU1b3JmMlk2
            NDBhY1RpalUrRS9JWnNsUkF2VHRMUUtNYURVCmwzM1FmQjNocmQvd0l1RktmWjM3
            OUM2Z21wOTZjeURjUHB0aTBOOGpEaW8KLS0tIHU2TmNSVjVxcTRYLzZJZ2lwQUpw
            cW03Y0VGTmIxSXFxblVrVVBkWkcyb1kKWHV3VGGYBIPjPPkk19f8i3/kIjxkHp2l
            No5zR6SfmdZJxxlAXgcLTh/UoR9+Do7A6/6dxfuv67dt0CgPg6ISTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-22T19:12:21Z"
    mac: ENC[AES256_GCM,data:zhJQMEYbUULynilI1ksS8ONnfmuq+UvVpOVFSCbGwu+scq6k1QUhFLV+862nKG7hVl/o2y4tcge7yEoynJTHR+Ur/4I6hYjTNtBByE8128gnME3pJZOrPo1oCpRz/PT6srNEgswHbFUhnnpzbZkI/o8PRba34X63eOrcEjswJlc=,iv:C6nmwqhi7QMkEF4PN7P1FkG+8fTjdcvl7UsDOJXpzUs=,tag:9ah5J7H26+sIRa3zF6ThsA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
