apiVersion: v1
kind: Secret
metadata:
    name: forgejo-env
    namespace: forgejo
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:EyfCtQDLVg==,iv:5UMJUwhHxa2U9MALHfnGQ7m/vh8yLlLwuLzume+FWB8=,tag:E7ysZGKpqVlkuiQgPVJvMQ==,type:str]
    password: ENC[AES256_GCM,data:qHiMCgPJLhu4tGNJF9QjT9KsoP1QPg==,iv:H1ormiPJDFGttBVs/VSK1gUQd3UnIQQkqUWi3r2guXY=,tag:5XOk0Lama36KbxjeVJAcUw==,type:str]
    email: ENC[AES256_GCM,data:KmxTL/WY+DN/7dpGFzcKuaPVbyOf+9g=,iv:qFYmCEMQlFv4oLGNFy1GmewNotXEEexg00btMnumHm8=,tag:khIBLGb1qsinVuqyF7x0wQ==,type:str]
    db-password: ENC[AES256_GCM,data:mP0SJ3SrqDedGkvJXj6/roMmg/+UCwckDST9cUthPlAedvBrrQtEjTKH/Q==,iv:pKeqAykAait0PgGi6Qr0Y8b4dHuGTThogjnaL9cksXw=,tag:1bMRxX7BAhHxXP6Qv8xvfA==,type:str]
    mailer-user: ENC[AES256_GCM,data:GgV6mwbtT//uyrCWXt1Pj5PgSzQZAhdWSQ==,iv:oQfNvWSAxkTKU9HUaiQWz3LPlTLYuOhWiB1ZIbWtXpE=,tag:nMnpIEMUOmi4zFHZxozB5g==,type:str]
    mailer-passwd: ENC[AES256_GCM,data:xjvxezeicJPUIGpWMdyXX8J/3Q==,iv:4ESSo6Ks1uroBj+Dnwr8nww5xlzUtKAm9DlVZE8Pj5E=,tag:bmsMkHN5P7U3P7enq/t77A==,type:str]
    internal-token: ENC[AES256_GCM,data:EWSCIe7XWAUfEEH3XZhvfArBtKN/CBiy1XkRyWVxX1Ge5o2Qiaq0Z3JyKAu13MYZMzy9a1JKxQEHB95qR1jP+PTtBXajeSuRCO8GsEp8V4iSzr2FLmElXA==,iv:4Z1sojyNuEArz2nnJMJhDntDc6kjJihZ0w/8mHyEnwE=,tag:MPoI0dobvRWyVk444X61vg==,type:str]
    secret-key: ENC[AES256_GCM,data:4PpFicxe4QUtzf7+xkabI3qyRBgMyT8fyKwulbkyif30ZvyhttMOWbeXBa1WlP5oLMqR2RfdVsaC+/+faBUZZA==,iv:fFo0ZIU2M5PsN4S8KD8gSxGv6rOuA+4SEUOCJSsLQ7U=,tag:3FU5URH5OaE6WiCnAv5eJQ==,type:str]
    lfs-jwt-secret: ENC[AES256_GCM,data:5rtba9RpAyUqYpCxSrfV1cOsgBRG45mONu1n57AIpOeeREZ+yTMQYPR4K1tibN+llORFM+aMV6bW+kS8UosZcA==,iv:ennFr83Cvv2HTOJYxqrk2rxPxvc3+9QPlcCze/yP+o4=,tag:eoZrFY8s1NN56J4ilJ+w+g==,type:str]
sops:
    age:
        - recipient: age1nx88s3q0e02zhyycd9q4lwxqts9e6cenrvlxfp7ka2ghaxzwa5hqhex8h6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNzZDNHZ1aHRtZmxqbEpZ
            QmNPQkVlb2o4REliaGtUNEdhNk9kckwrcTFBCk9wUmsrUUhUZlJ6QkhaRzZwQXhO
            aHF1TTdXeTk0SXVPSURVellKUEtiWXMKLS0tIDlFWFJzNFgvck9NWHNpdmZlNHlT
            QjNYdVhrYk5mMnFucXlGVHQvaWhyMVUKSwnJ5pED7w0B/5/i9d0BTuMtT/TcgxIC
            ZT4kRpn9XKsjKpvXgBuienM4tAIffVVwfsbdWGujQeRv4Bgfaxrq5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-06T19:22:23Z"
    mac: ENC[AES256_GCM,data:eHDp5RoKLv+mOj0M0waRTuLKt1b1mkYNYtIRHTL/c/CzTtgsITr+gTMZy+U9gF8WXAhTmYvNJ0cLaU6/4mfQsx4GXRuXutZ6A4s1Kf9Xx4mToB+2S4YxGjhbnWIZlT8mm6yQ7CdTNLDrPdQtbRqR8FzSOWh8u3TGZlKnizMUWvs=,iv:nngFZcmfPTgx6gxhoISJHdRA+Y3sGjHnrq+zp1oe4tQ=,tag:VrVCIS+Qzbpc/qsvRHxR8g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
