apiVersion: v1
kind: Secret
metadata:
    name: forgejo-backup-s3
    namespace: forgejo
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:TvHPIHwA3ra5G3wQviMUbSuaVO9XfbuSeOMOrxtsQ1w=,iv:n0fLcgY2X/LIvnjf3WxlU3i8zBWUFikPa2Vik0rXAwI=,tag:J4nqJ3hu7AuveeKVaAcLqw==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:yVn/gHuOrnOb9CDdbmLTi9gUWDeX2tOVdDTTVjvl9j1+TxkzC9IfiBdYoBrg9CitRMMFaSi64zLikXZ2GghUUQ==,iv:L6mn8H5aIOhjYU4gxSEEa6wsf2U81uiw/kSTs5NbqU4=,tag:CD2Om1ENUZXxsWHrnZPMVw==,type:str]
sops:
    age:
        - recipient: age1nx88s3q0e02zhyycd9q4lwxqts9e6cenrvlxfp7ka2ghaxzwa5hqhex8h6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWUZueTlTWCtaSVVDS3B0
            YnpPK000eWgxVTFhM2Jad1dpUlpJM2FrT0hvCjg1TkRCZ2YwMkpOVEYvSHBpcTFW
            bThzN2xVM1JQeWUydXU5bzltZUs2bjgKLS0tIFM0VFZSbVR2VlAxekY2bGo2K09X
            elR6NitQR05temZjUVhYVEt1WXJJM3MKiTaQV8ECJFg1hvdfR4V8/boUVMQLAwtP
            IddOhf7hzKhFfg54HV+4ylJrDP2LhCe+RSATjUDjyE3yh2JukV+ldQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-18T21:56:57Z"
    mac: ENC[AES256_GCM,data:beoAsyEzjj8P0yyC1cDZCSfNXZ7rdK1sA3pmgsSK+u+y7KCGhL01qd2c5pI70r2rufw7rk51LwwEkfC3kb+aqw82exnpfC/qGaWZj9g5Q3br3FEUiYuZl3v9aMPBh3316r88l4Mo/au8+KVDu83+WBnyHW1+pk63Dt3UyZSox0g=,iv:jkWyJiuHx6SIXHq4+DtbhHedihyvyf4bmQ3R8yfp+GE=,tag:HqMUPCCcVtoP2CKqXZAo8g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
