apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secrets
    namespace: forgejo
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:dXc25GpwBsQCimC8nn/wvBxC2PmS1P++1CQ8XjIGE4k=,iv:HGqNBkffPvZgpLvXa7k2zC1FYyp0tqhCnRZ+u/ZFzXA=,tag:iFM1ycoZh68ZZjo9z4aC4Q==,type:str]
    jwtSecret: ENC[AES256_GCM,data:GCJywBntP2S455x95wDf6RAWVLKb/fjbGQVM67OOFvWxZBowxxV6P5BRxFV5EBevmuiVf6ZoiLJmJI2poXOhYw==,iv:+2QBPJO/wXO31lMAd9JEbGSrpNlc6kps/KdlIgecq8g=,tag:dLyIXps2ijeK/G+qrfpo0w==,type:str]
sops:
    age:
        - recipient: age1nx88s3q0e02zhyycd9q4lwxqts9e6cenrvlxfp7ka2ghaxzwa5hqhex8h6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0U2pOcTYvYVo2ZlVsUTZ3
            R20rdTgvTWZBZG42TFF4cTZhQnBQUWhoUlJzCnczWm4zb3BSSjZSRXNPVmR3bWdE
            cTdVTHVqT1J2MEF3NEZkbEN1dWtOeEkKLS0tIDg2Y3ZaeGcyM1d0SjBnbzBEelFX
            VVh5YnBXeUxnUC9zelpZQkVWMm5LUHMKe01QShZC+dnf2Xd/opu6dGHyMfDtOntr
            3uiaXMqhYGOEeZW30rl71OsSyPWylifcM+qyhstnKJkviYAeEaJH7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T01:01:05Z"
    mac: ENC[AES256_GCM,data:+Dq0d5j27geN/Q6gN6VoqJKhlT59au0sMW1oAYG8qejXO5gY3c/dUwcuf4p7OgYZSYUI50yFGvPTgY1gUQrKFQyW0pAFpyo+zCaYgn3HHM4rQ/HCQk5fPri0um8BucSrjuHoi4lNGU13UNCyGVvTT+D67OoIW48McO89y8k7sZE=,iv:ttyRzu//AiyB+PENiw696iArfr2C2kuZgXJ+WvIi0sI=,tag:9xrSRCEOSVccku2sejDK3A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
