apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: forgejo-db-monitoring
  namespace: forgejo
spec:
  selector:
    matchLabels:
      postgresql: cluster-example
  podMetricsEndpoints:
    - port: metrics
