apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-token
    namespace: forgejo
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:jF3pzlab5fuIpKPI6THTutJbeu8zKgPhE5B3NOCyHUhFQWyfbYinPg==,iv:83FyCBhIytFfJuM7I0xWmbvTUchz5YydqpbInhO7iVc=,tag:gcJJuE95e+fZADo8mrQikw==,type:str]
sops:
    age:
        - recipient: age1nx88s3q0e02zhyycd9q4lwxqts9e6cenrvlxfp7ka2ghaxzwa5hqhex8h6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SURTSFZjM3BveUp2NDBC
            cFpPUDlQeHV5OHNubC9RS3h6NGY5WWxXR0JnCnk2aC9UNzlOZFJqTzdpNWhBdGE1
            eUZ5ZXRKNWtXY1JYQVJhYmtqUkJkSlEKLS0tIEUwTW9GbW5jNjZyMEV6RmFWUkY0
            ZEk2NU1LWk9kaFBMNlcySlFCN1dWdFkKig7NK2rg/1YDC6GE1wqiafR0i10pn8Rv
            qlep1iRC00mQtgoRadvNcW3/HfBcs5BNNomMws0Xzv8n+u5i9yUyfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-27T19:43:01Z"
    mac: ENC[AES256_GCM,data:2kMTz444qtx0HqNcvpcT7CsAEjkLq4s18JnmIF/ht9gbHMOM2bbmCKDxKPBhkKOWtMjH6Yy0ktMHRS3b5SKeFd4Oi3JUYTKG45kndexUc9GWa9ox05Ebu2Wshs3Ylt+m87ulIGDi7XWs61WnecErxM+IJ5SYvb8aFAF3q4QA1fk=,iv:tpaM/A6bGzaq+83sXEal4Dpb6zEqh1UznPGv54ZlW2c=,tag:Jc0nQ3gCVZHnUWqiwcSxtg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
