apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
    namespace: forgejo
type: Opaque
stringData:
    runnerToken: ENC[AES256_GCM,data:OYISDmy/CMavU478Q90XdQZDgelyDQjx9/LSyHOsYXdCfB8SV7z/pa/1ac+5Ypbb8JXSGDAdnRFEEvfXGE5z5Q==,iv:ZJhrexnHeIMZBhli0Be7ftL1mPSkjtaJurxStid6vx8=,tag:lab/jAbQFO/lWurcBzTBeg==,type:str]
sops:
    age:
        - recipient: age1nx88s3q0e02zhyycd9q4lwxqts9e6cenrvlxfp7ka2ghaxzwa5hqhex8h6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqR0trWVNyVExnUnNBN1g4
            QVFBWXpVZmxQSUZvM3NEMGxEaDM0TTgwZUFvCit4VmhlR0dGQUNCMnhWelEwdjFP
            N2dOR0YwMVd2V0xZZzBWRXAvR1VrTXcKLS0tIDJNamdmQzF0ZGR2TnFMN2wxNWs2
            QmtweS9EbVIxQ0dBTkluWlA2cG1UY0kKdFL3bl89Vj5VkyhGvUgSVV8XurtRkz4q
            FKVkBwPAyzpkD8UJ+PMaJ4ha2f4jmu2iamtxMucZhbe3a8jagtx05w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T01:01:05Z"
    mac: ENC[AES256_GCM,data:ZZNVR9Oh5Ka1ZRqf3nmodkwPEdz78CaVl541qPQ6Od6pHeS5O6/pfqwvJroSTQVPxGuj1b5xanqbY5X5xGTqz3pIHhj65OqqiP5OYcZx4QiKAzatIoZTTCNo07kWIrlPMXUuWKGB0Oc4FX7LmA8YuU7xpMpsHG3rojZ28mH8OSU=,iv:uqscR0LVAaT7DHKMXaqoJXwBgiZ/q9HHQcuuSLGHvVM=,tag:SwC7mOHrgfOYPYlL/+5+sg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
