apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-config
    namespace: forgejo
type: Opaque
stringData:
    runner-config.yml: ENC[AES256_GCM,data:8N1AQh7vPTemy50a88GPnPBr84qk+vkR4lh6n+po3Fyc+AvvlznDA3Ir4QszE/Xuovp+dvo5kCW2R+xwPIqweS0v60KO7b0ToNeDZYa1nPKVl2s08ScIbgqsPtCYBs5nnY7lfmUN+RYH+vaUc7wXUjOBVapdzqd1LSDqKlVCC3Dgdyj/zFlQSKSeIGN4ZBoPjjkWig7wpC7Oui60hdtiVakiQsPgTh+DeUcPoyaR50QbxlV9l8658SwP/osFuGxCPwLotRt62KLmvV2eCKtJrEj5W8t5ql0rC2n8T6sfkSifzS4ilxX9l3qYOM4axf4jZYYimR7NLUnl6/ssLjJNmZGBo7vDLW7DA9DyjmAlJnR6UXa4mmMoeLovhg88XdwaDbAfvJPmMfkuN7nURySBPu74MS1Ytp+RAVUQ+VceiQ4iA1ibmTU0jey/E+bJuyX9UO8G9/GeX427J9LkqxQgh4gsqbz7YW6jOGfHUqJy+yWAV0tb5NRNpmrt/LQRq4fOIBo+50jp8oWW1Medc4mfOqPhO981frFh/fAhLxw6KenQU50GHtUnyX0vJMTdRsL9kivVb0WYB9T0dZm68uMN9jaa6c6m/f80ew==,iv:ccRFIWY/GOVW/myEHYpxYe0VxcObufat94uwBAjJaIE=,tag:t2M+YhwsdUdbd8Y5zVHdKg==,type:str]
sops:
    age:
        - recipient: age1nx88s3q0e02zhyycd9q4lwxqts9e6cenrvlxfp7ka2ghaxzwa5hqhex8h6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OUZKVm1laTJ5ZWFQbWZa
            MnV4QUNyNnQ3N0RDczhqNEtiNWt3N1BxNHdvCmFiT0l3czBnT1FwY1RiNm12WGY1
            REtaYURTSVRSU0FvY0MvWHVKNThyYWMKLS0tIC9kazBZR2pUUGVkNzZFS25ScG5F
            QUxweWxtOXY0YTdyRVRZcDVDa0Vpc1UKAArkVOUI+/pGhTWr+aytndYcwxrKj7le
            QvyjMZf/LL8FxkcPeAf9nU1+g8KaG1mlg0De7bnR7I+TreQ8Jas91A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-27T20:10:54Z"
    mac: ENC[AES256_GCM,data:xCrt0q1lVAnZB6O3tmTFJgjbD82z/LrrMuo1cRGByvW4zACHIigtdVIW24pHdcJ7qMmxLy4zFv0Kki3jlSPAm93/F9opEpdd6HUQs7Hcesv4obYa6V1EdFqHFH583G0WU5ldQL7V2sQ/Vlf2uhb3GDgt+3YLcKceIW8uTpC3ZDw=,iv:JZk2QvUAilgmkKbEh6JnN4lkJMU+7ffQhoMznekTmpA=,tag:iHkmKK3IIGbBE3357EuL4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
