apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghostfolio-postgres
  template:
    metadata:
      labels:
        app: ghostfolio-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:18-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: ghostfolio
            - name: POSTGRES_DB
              value: ghostfolio
            - name: POSTGRES_PASSWORD
              value: ghostfolio
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: ghostfolio-postgres

