apiVersion: v1
kind: Secret
metadata:
    name: n8n-env
    namespace: n8n
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:2gfD3oz+HJm44Am5YLYnmyArcvooEaBS4S9xVrkKick=,iv:cYi0jM/ujIPbJUp4De+2Gm2eufCfj5tbIWcHr8w7+KQ=,tag:Rr+DD5ceeV4iD4LmJIBGKQ==,type:str]
# Chiffrer avec : sops --encrypt --in-place apps/staging/n8n/app-secrets.yaml
sops:
    age:
        - recipient: age1nx88s3q0e02zhyycd9q4lwxqts9e6cenrvlxfp7ka2ghaxzwa5hqhex8h6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0S29wNmdGQUU5VHIxeHJm
            ZXpHeHEzUjNRM0JqeE9rblFiV0lCWThJdUgwCktFZVFHeHNDMkdVRUd6Z0FQYU5E
            TEQwK3dBS0xvUTJybmYwdUh0TlNQOHcKLS0tIHduM0pPSXl5Wms4Qk5oL2hIUFE4
            NWdtbnBTRXNQdEJDTlB2eElJN2JidjQK9MVAx1s/p0Xx7uSWmgLZNHToCilNF7rK
            SNrShqAwHxnOSon6jc9pqy6xJtcarPP8Vmc1+KQJiGn+tc+klpWNxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T18:56:46Z"
    mac: ENC[AES256_GCM,data:nYZBNUInMh3ODNS9qBIXaSMidH4atyYr2hrFLu0EGi7xlaR9s0naB9vOadcgN2HrYf/KIalZLmpwP7OWrF6Ow8mVGqCF0VJ4w2shBZ5RrGxOphLArLilz2rKPDRic2JLweJ95uZMZxtI3edeDIwVwMcx2GRXQrjo6TxDNKE9jNI=,iv:fhbU4+WWmNglY7GoHssGYaGvzpoFVYXBISDMpfN4Ft4=,tag:SqocRI884uXpgfDmYFfgQw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
