apiVersion: v1
kind: Secret
metadata:
    name: n8n-backup-s3
    namespace: n8n
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:lU2BqXbKuNcX39PqaGOmZhdwL/sRW9rAlUx6rhW1Rsk=,iv:+dGFRKhXmkPq49cyjB4nA/3/tgDZK7+CyN3K5iH0ECc=,tag:8Cvg2D7TdRnBfruOh98B2A==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:0iPlYlzQzmgg6H1spHjc8puVtUuxfutf8/pMaXh1UeOfzJh/TAjG0stLvi/3B+RafAUjOibteh/iHGQeaflXvg==,iv:lihsLyBWZF7pTwz7xkgpe6z6PAdXMvbPLPCiPGTxhP4=,tag:zX/hhD0iPjjBo5JR+aTEKw==,type:str]
sops:
    age:
        - recipient: age1nx88s3q0e02zhyycd9q4lwxqts9e6cenrvlxfp7ka2ghaxzwa5hqhex8h6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMmpXWFhQS3VVMHR1ejJ4
            VFNIV24rZlBGQ21iRTY3Q1haZ0tWdzBQZHlZCjJlSEVxaXIzckxxd1V2MzVmV2Fm
            UndlMk8vc2gzR2duZW02d01DUFpoRm8KLS0tIHExY2hGd3NSbTlIaWQzMjJUU2Fv
            QUV3QXNSUkVzem00N1BBTUVIRUcxS0kKVNLkFtVKifSXoUjb+9FpNjI3rwDFSnwR
            y/MGq9GSnmSFYkGProaSiV9WJfWjaKrd5LQgWCV77GfhFCHMALPTMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-14T19:07:31Z"
    mac: ENC[AES256_GCM,data:Cql1tXyCINd42ApAsBkMCmlX+KPSvEOMn+gjIO7kjc+YLmiXlrOs6muAO2DvtEEhCU3pYOzs1bAQNwYZ56h9k5M+oxYkPJTybqmKe/7LAgzlHt+wZ0xa9tW7dXpxhxXs96/9AwNpiscBQtKX9353ryoxJtcnBDxDdU+9Kr7Kt6g=,iv:gOH/pahAyiLUi/njekKM2z/VhTxvPjtxtzHTrn4o9e0=,tag:SrMQc6JxYFx4tRFLwkLu8Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
