apiVersion: v1
kind: Secret
metadata:
    name: n8n-backup-s3
    namespace: n8n
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:RFzwYe0/nT7byq22mjSAYMLWrmhySNZ0,iv:O0Z80Mwlx2yDNV8QN2Bca7m3DLVR5XyAJTdeGiWDI08=,tag:VlegIWRo2RB+jweCP2QByQ==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:HbM0wK8vBWnlSZBbMmYUCDQCHT7Cd0qWTGs5Fg==,iv:tMSBq4X9KAd1+X9xbuIsXDOJaoe8CmOvmT/9cTWhaso=,tag:PDtRaxzaxWzCffW678XyIw==,type:str]
# Chiffrer avec : sops --encrypt --in-place apps/staging/n8n/backup-secrets.yaml
sops:
    age:
        - recipient: age1nx88s3q0e02zhyycd9q4lwxqts9e6cenrvlxfp7ka2ghaxzwa5hqhex8h6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSlB5R3VMZkNzb0ZUcGow
            T1QvLzlIcmxGTTdBTjNzWDB1TDV6dlJ3ekg0Cnlxd3l3ZjRPbWJ1T1pVdHg3eFdT
            TmdkTlIybU9BUit1TmNKVXNUM2xUWWcKLS0tIHB0Y2hHMzZEeGE5WjJZcCtYRzRo
            Z2xVSzFGR2RpeDhGaUVRVXRVNktuVWMKx3TM8EGr8PwzA1G9P8QSwsjI5AtNDGS0
            2Yx38Gm7HuPcpNIcLGYCX8fdSDwBHD6QTN9a3vV5QfoRnQ2vTOMj7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T18:56:46Z"
    mac: ENC[AES256_GCM,data:PrA2fxUp4+y9Tikq2DwukVZJfBvmauIwlHlDsyueLDqLXYAZHnUqLtzvir8g3WZRPegUYIqUCnlode6dG7PGllaIdFC/mZO0ow2z6g7w+cnSr/AjjnuqnPF8FReU9DF5IwwbpRYcD8/FteGyN5eOZ3XQ5FVpZYVLnE0BSz0RXcU=,iv:XQNvIBUTSD+irjQiHoCXvclx5/KLYw32msQbWcN9OO8=,tag:ztTKWLnsAmX6e8P7p6UaqA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
