apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 30m
  chart:
    spec:
      chart: homepage
      version: "1.2.3"  
      sourceRef:
        kind: HelmRepository
        name: homepage
        namespace: homepage
      interval: 12h
  values:
    service:
      type: ClusterIP
      port: 3000
      enabled: true
      # className: "nginx"
      # annotations:
      #   nginx.ingress.kubernetes.io/rewrite-target: /
      # hosts:
      #   - host: homepage.example.com
      #     paths:
      #       - path: /
      #         pathType: Prefix
      # tls:
      #   - secretName: homepage-tls
      #     hosts:
      #       - homepage.example.com
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi

    persistence:
      config:
        enabled: true
        size: 1Gi
        storageClass: "standard"  

    serviceAccount:
      create: true
      name: homepage

    rbac:
      create: true