apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 30m
  chart:
    spec:
      chart: homepage
      version: latest
      sourceRef:
        kind: HelmRepository
        name: homepage
        namespace: homepage
      interval: 12h
  values:
    service:
      type: ClusterIP
      port: 3000
      enabled: true
      # className: "nginx"
      # annotations:
      #   nginx.ingress.kubernetes.io/rewrite-target: /
      # hosts:
      #   - host: homepage.example.com
      #     paths:
      #       - /
