apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 30m
  chart:
    spec:
      chart: homepage
      version: "1.2.0"  # Remplacez par une version spécifique
      sourceRef:
        kind: HelmRepository
        name: homepage
        namespace: homepage
      interval: 12h
  values:
    service:
      main:
        enabled: true
        type: ClusterIP
        ports:
          http:
            port: 3000

    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
    
    controller:
      enabled: true
      type: deployment
      replicas: 1