apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 30m
  chart:
    spec:
      chart: homepage
      version: "*"  
      sourceRef:
        kind: HelmRepository
        name: homepage
        namespace: homepage
      interval: 12h
  values:

    image:
      repository: ghcr.io/gethomepage/homepage
      tag: latest
    
    env:
      - name: HOMEPAGE_ALLOWED_HOSTS
        value: "0.0.0.0"
    
    service:
      main:
        ports:
          http:
            port: 3000
    
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 200m
    
    config:
      bookmarks:
        - Developer:
            - Github:
                - abbr: GH
                  href: https://github.com/HermannH34
      
      services:
        - Homelab:
            - Homelab:
                href: https://grafana.quickyrails.com
                icon: grafana.png
                username: admin
                password: hermanno
                allowInsecure: true

      widgets:
        - resources:
            backend: resources
            expanded: true
            cpu: true
            memory: true

      
      kubernetes:
        mode: disable
      
      settings: {}
      
      settingsString: |
        title: My Homelab
        headerStyle: boxed
        layout:
          Applications:
    
    persistence:
      logs:
        enabled: true
        type: emptyDir
        mountPath: /app/config/logs

    ingress:
      main:
        enabled: true
        labels:
          gethomepage.dev/enabled: "true"
        annotations:
          gethomepage.dev/name: "Homepage"
          gethomepage.dev/description: "A modern, secure, highly customizable application dashboard."
          gethomepage.dev/group: "A New Group"
          gethomepage.dev/icon: "homepage.png"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "homepage-redirect@kubernetescrd"
        ingressClassName: "traefik"
        hosts:
          - host: &host "homepage.local"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host