apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 30m
  chart:
    spec:
      chart: homepage
      version: "*"  
      sourceRef:
        kind: HelmRepository
        name: homepage
        namespace: homepage
      interval: 12h
  values:

    image:
      repository: ghcr.io/gethomepage/homepage
      tag: latest
    
    env:
      - name: HOMEPAGE_ALLOWED_HOSTS
        value: "0.0.0.0"
    
    service:
      main:
        ports:
          http:
            port: 3000
    
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 200m
    
    config:
      bookmarks:
        - Developer:
            - Github:
                - abbr: GH
                  href: https://github.com/HermannH34
      
      services:
        - Applications:
            # - Homepage:
            #     href: http://localhost:3000/
            #     description: Homepage Dashboard
      
      widgets:
        - resources:
            backend: resources
            expanded: true
            cpu: true
            memory: true
        - grafana:
            type: grafana
            url: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:3000
            username: admin
            password: hermanno
      
      kubernetes:
        mode: disable
      
      settings: {}
      
      settingsString: |
        title: My Homelab
        headerStyle: boxed
        layout:
          Applications:
    
    persistence:
      logs:
        enabled: true
        type: emptyDir
        mountPath: /app/config/logs