apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-config
  namespace: forgejo
data:
  app.ini: |
    APP_NAME = Forgejo - Homelab
    RUN_MODE = prod

    [server]
    ROOT_URL = https://forgejo.quickyrails.com
    DOMAIN = forgejo.quickyrails.com
    HTTP_PORT = 3000

    [database]
    DB_TYPE = postgres
    HOST = forgejo-db-rw.forgejo.svc.cluster.local:5432
    NAME = forgejo
    USER = forgejo
    SCHEMA = public

    [security]
    PASSWORD_HASH_ALGO = pbkdf2
    INSTALL_LOCK = true

    [service]
    DISABLE_REGISTRATION = true

    [repository]
    ROOT = /var/lib/forgejo/git

    [metrics]
    ENABLED = true
