apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo-runner
  namespace: forgejo
spec:
  interval: 30m
  chart:
    spec:
      chart: forgejo-runner
      version: "0.7.x"
      sourceRef:
        kind: HelmRepository
        name: forgejo-runner
        namespace: forgejo
      interval: 12h
  values:
    forgejo:
      url: http://forgejo.forgejo.svc.cluster.local:3000
      existingSecret: forgejo-runner-config
      existingSecretKey: runner-config.yml

    runner:
      labels:
        - ubuntu-latest:docker://ghcr.io/catthehacker/ubuntu:act-22.04
        - docker:docker://data.forgejo.org/oci/alpine:3.20

    container:
      driver: kubernetes
      kubernetes:
        namespace: forgejo
