apiVersion: v1
kind: Secret
metadata:
    name: beszel-agent
    namespace: beszel
type: Opaque
stringData:
    KEY: ENC[AES256_GCM,data:shh8HM36IHyZikVlT6XaUFQW9G2JpxNyZnTdisd/ForXTsf7RCqZiBz3J1jVURF6IHAU4DvCGJxaU6Jda90LcbnWuoTiJ9uyMpi40ZIg+E8=,iv:MBxD8gLdJG6N3L3snrKaFJ7atpbwRkneQ+3dxR2yMCc=,tag:eO6gHFI7pUsqAtZ+oUJO8A==,type:str]
    TOKEN: ENC[AES256_GCM,data:DQ0w5wAutyliV+vtjfSAzmVr58nBF2RjeUZXE656PgKbFjU8,iv:QVylLJV371s4290T8AlUx94y/kfaRM0DkBw2VSOET0M=,tag:1n/i5ql1+Jvo1oxNIGjKGQ==,type:str]
sops:
    age:
        - recipient: age1nx88s3q0e02zhyycd9q4lwxqts9e6cenrvlxfp7ka2ghaxzwa5hqhex8h6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSHRQb1k5a2dRY0lRZlVt
            bnlTeENHOGZkaXAzRzlEMjhkQ2hLbWNyOEVBCjAyL2lZeTN3dE4wRW1abTFXTkdV
            SjZaejQvU3ZQRk1XbHc3Sm9wcnVEcUUKLS0tIGFWc1dnNnNmQXBVcytxdTZVMFNm
            c01KKzR1b3BieVgrTUM2S01BU2FLemcKSd1B2etjbphOMj+MyXLLf6StYhP6e5h2
            iz2x+JX4CJ4MMW6EzB4YxyCAa+ZfwDR6i0EKTy9RRf3t1Z7YPuzOjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T18:31:22Z"
    mac: ENC[AES256_GCM,data:L9LoQbXYs8HghqtAWyucRnE8LQuY2eeUk+2HPFp9SfdMxW3FgChweSl10LSk54Ac3eUaVdRze/xMrXoXtrRdZ5H4R9DPa+4T/d1n0Pk7FDXRlEiaSiX+nWMKM4Sn+h93+BhVTDnpPXqyKTWUkfNCwybIb7q7FSt3tN5vEDI2jiU=,iv:1/4RcRwt8AynL4trH4Nz+NLVpf4FW15Ap4bKec0T0EY=,tag:6fTS7yVy14mh0p+E/uS9Uw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
