apiVersion: v1
kind: Secret
metadata:
    name: iterato-env
    namespace: iterato
type: Opaque
stringData:
    DB_HOST: ENC[AES256_GCM,data:2dLrhcOTFllKD2RSzNR8p2gBVs9kRrqfpRxfHjuusW6r/Sxom++r,iv:o7pX//bfDjvjv4pmOgzPhBVajx4fVGL1im9+4xMCoTY=,tag:tqGTbNIEzZAmPX5nobDDXA==,type:str]
    DB_PORT: ENC[AES256_GCM,data:PjQoPw==,iv:/8cHfWj11uichXGS+3k1KVBsTD9Jy4PjvnuA8xCxgp0=,tag:JDxwtuEKGHmdsERMxj4Rpw==,type:str]
    DB_NAME: ENC[AES256_GCM,data:OAiLooNtq1t4chp0iYU8SWFm,iv:qY9zxKI2+w8aD/jN2tkS4BjVyP08bi+++orXuWlOnj4=,tag:HtL3ssxMGO/nnhRX9xJmXg==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:E9YCZi01OA==,iv:cUbBPz5Mv67UxbPOuaHpCM/fjycpYVTmQ/qa1YOS7zk=,tag:BpokCP/U15uwIzL/65LLaw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:ivawVzSdQO8vxDGFZulgZB6GqFmPQKyfNNNRCGohhh4=,iv:5K7ZVUZs8FK5/x0y2K67LJW5L8ERCAfmG4PQ7ZSBlQo=,tag:Cv8EM5S6m5hYwy+QdZGL7w==,type:str]
    RAILS_MASTER_KEY: ENC[AES256_GCM,data:Yz1LVzefGOxYZuhrGVMNBdB+LrGMLsautIKT1LalWhk=,iv:ML8EzW1g+hTyWZTchZlO2ytB5ZUKaXSNn28ntY4+oAI=,tag:jhextVoEKHjWUfdffmJOHw==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:qo2PRbjtVnDkhSg1Q3vYCmtsvD8O2SE+zyjxL/wwTmDX5HnebAv82+CG56ENCFAP260qrY1tyIqYvFwOgI6XT72FqAi1U60M6yoaswf5Sm4MKZX2d11N8gI86FPpi+5GmXpFgfWRVtypEWqjxE8yi6CgQD6//sCo+5MR09PlkHc=,iv:Hokj0hu/vyHTZOI6pQqJSycUrqhy+xMQDDXierRtWgk=,tag:IozUipqCHEE7QXiFMxhhRA==,type:str]
    RESEND_API_KEY: ENC[AES256_GCM,data:lGbxkSBdOoAuG2rycWxkHl1jZVTnqZIvp+GtL/eRlLGyEi+h,iv:cy0Sewrf/OJ4KfYGLnPSWCAjMHeHxJPTJPZeOwf2iEU=,tag:i+3lbVZHoH7rm3XySyqVpQ==,type:str]
    RAILS_ENV: ENC[AES256_GCM,data:nVSsNS7JcgwUfg==,iv:zdTUaAzgAjONFYB7UIgbgMsd0S5kP4pHA89zat973CM=,tag:7LvptrsxyrUDrj80+4Aixw==,type:str]
    PORT: ENC[AES256_GCM,data:jABbEA==,iv:Eo2RTW/GMk93zgIHHulPMnaPSlZt4kIQdzsJ8BvJLiI=,tag:pWF1F7gpgPOn50JavDTtpQ==,type:str]
    RAILS_LOG_TO_STDOUT: ENC[AES256_GCM,data:qBRfPA==,iv:G5sGEixtVmp7TVOc4t/70RIf0/iQ3bjGCJUGVKfNUz0=,tag:8j0Pb8jjKJF9R5SxVh3nnQ==,type:str]
sops:
    age:
        - recipient: age1nx88s3q0e02zhyycd9q4lwxqts9e6cenrvlxfp7ka2ghaxzwa5hqhex8h6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2STdOQUN1c21CODBnMHc2
            QndUMkhLQ3NHckpzcjVwS1p0eEUzT1RhR2lzCjhYS0xCYXVFN1ZneFpFaS93ejVM
            YTByUnoxM2hQbmtkWW40NHFZR29jR1kKLS0tIExnaGdTMTQ1d285bEE4OHZGVlpa
            L0dhUlhuaTI1VHc4UTI5dFBsZzVlazAKgx0Ql0nv6ioY+fbs2/fTVihKy5xrW0bU
            BDEQSntpo5e9sMbP+TLEIgKEkb+zMwf4kdzXNDTHQe5ToZ0BWecSKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-10T20:51:21Z"
    mac: ENC[AES256_GCM,data:MsV5cR9ylIgY7Wx4alHACVDR0LYxkhfGBqCjD82n65yGNgLSl8DxL7RIGy2zEWh1xdYMJjhk5A0jvi9rgGCbBaY21uuzblb/5QK/fXJ6k+r+hXSLu8bxEUz9oWIGg1nWuEYgFbA9muckH52fGmZwOG+j+psLESJS3gcTcXSzLP4=,iv:7S7Ti9u4d6g8T+167w9Lm6z36XBHh66w9wBVwWDPs/4=,tag:7LZUNc8vhZX5t51N/WZMGA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
