apiVersion: v1
kind: Secret
metadata:
    name: iterato-env
    namespace: iterato
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:Oj3wgOh6iV/vtTwTsktZaMbctZjzTwJ8RfbN/cPAg4lLEqUjICdLAzFnv1xvSe4iW7TI7EGnT0Zdb/l+acHtM8Hf8KSe7ID9ro7ppV9hXxUNubyEt2TeLFtQTDWVfm+yIq8Bryqv8RM873m5sYg94OIQiePM,iv:HJjmcXo7nMXYUeixt2xETuNwYrW4289ZmABa+kYyCNE=,tag:prpH3vNqkl0AG4cSm9OqOg==,type:str]
    RAILS_MASTER_KEY: ENC[AES256_GCM,data:nvIPfU3Q1F1S4cdTBDRnfp9mGKjxhqc5jvhAoFvqk2k=,iv:ir/W4BaN+HKlfZxKXMilAO6IyBqGYrBu/Ej06AKCqtQ=,tag:mkF2uKtRVsAnQnH40vL37w==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:werQdHUWrsX9jaHGBJiQyMsbM6H3I6cklbYPaMLP9ngjMT8HD7sumNJ1dKRxcNowwNtanmZjMHsTo2hwCk8HPV2Fv8/bGM3aqYjcXQXNueTCGC5OjXzw3lkSI+En9PcIKuvNEpauDftk+eOzHTd6phYgwmLyqe72W5p3fe2A7cc=,iv:eYHR7GpV/oBVmwYeWTlbw0e21CwU26u/EqUx3j7AzTw=,tag:sZJv6hb7dyR15LdDjNitOQ==,type:str]
    RESEND_API_KEY: ENC[AES256_GCM,data:Xm+aVYcaR7wQ40+vacBYUgAdA78hjmwGu/bjol7ozLKkICG/,iv:LmCNs7o2GmhcogSgk2E1u7nwEH29LACzWnVLlwv2UYI=,tag:cr76aTh3v0RIDQuoCM+ygA==,type:str]
    RAILS_ENV: ENC[AES256_GCM,data:FGYDTeaOh+96HQ==,iv:gc78J/jyz5SftJgr4jIYkFLKoEpmyeyB+rt3Bodt2WU=,tag:KktFKvs7QNcCc30pf+Qccw==,type:str]
    PORT: ENC[AES256_GCM,data:6l4MqQ==,iv:pBLgeVAAEwOXK3zKvIornWDFD1WsF2C5uH0QVKJsnJY=,tag:zEMR/DdeylA5a2YeH6P8yw==,type:str]
    RAILS_LOG_TO_STDOUT: ENC[AES256_GCM,data:Yq467w==,iv:c6jNaK/eiamytmjv6rnml3JHd4vIuqHIuO6A9oqwyLw=,tag:BiZkQ2LFp8poSzgFiyyZrA==,type:str]
sops:
    age:
        - recipient: age1nx88s3q0e02zhyycd9q4lwxqts9e6cenrvlxfp7ka2ghaxzwa5hqhex8h6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WDBnZEJuZXQ0TTh2QSs3
            R09ybXU2TWJ0YUdhNmN1R3pVRndJdk9iaG40CjB2NnVlMjRlNWFjQUxrYXJBY1pu
            R0NWR3VkUG9SUS83S08zYzJwUGNUQ0kKLS0tIGxzTGpwSEdmV09Cd1Q5U2NTWTRX
            VXQxWFUvYjhnRUsvQzlIYkFvUTJIK2sK7t3noSCdKJCh6zmzU4t4cA9H3/yA3HUn
            6Om2DGl+pX6St6fv7Lw0ff2Jaea/7XKY8R2U5DV7aG9i2WDp2MNi9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-10T19:58:08Z"
    mac: ENC[AES256_GCM,data:2lS7e0XHaww6iuyZyXPrgYOyflv3fzrflUiw8uE7wyckW6Xozc3Vns3p+KOG2xvrvkWzSLgVb03jkta9ds/h4/QlzLICJxZo3fmF/yhH3O1CKPzCMpTbUnn3nJe6EK8n9Rhl/gzbNyPRee6pImhfwGldiuOMayvFUVVSKMhJIy8=,iv:7Wj05wAgy1x1gRyB5tX8BMtvdtZCM4ZJIrQBRs/COBw=,tag:kC+iFPpfSUCgJq7qflVElA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
