apiVersion: v1
kind: Secret
metadata:
    name: iterato-backup-s3
    namespace: iterato
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:iChjGx7JOZSutG/4svIEiiaBXwYbj4kWxW4rVZlNQc0=,iv:5sgp8SV590Fx1GXb2MZrd2dvoPW/mgUiIBzVb6JqCCU=,tag:wQg8JunRfXxqpW+r9JzBUw==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:TLfWStddwVwLCLeqdyUd4ONOzdJXSSxQBDxQP+xO1FLQPI+y0nFW4pNWvr1VG/flw8dP3HUYUQ3/KsGczzXPQQ==,iv:c+6SBoeMQpyFjwOzhfiDwHMvdNaZ9bzgHo3eQRazaF8=,tag:DFg9xhD13DDS3Jg2sJQlug==,type:str]
sops:
    age:
        - recipient: age1nx88s3q0e02zhyycd9q4lwxqts9e6cenrvlxfp7ka2ghaxzwa5hqhex8h6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZjF1RXhtbXJmeDFBenh4
            aUpjTWpsY0tVdVRwRXpyS0VMY2ZueVd4R0ZRCmdXajhia2lDZmpaTmd3RjFNUFZT
            UlUzSm5vWUVFYWVKeTUraW5pdXdmZG8KLS0tIFk0Ly8wbWRqOGNoUUFTVDR3cEM2
            MDc2K3RCWCtJTGE1dFlEU2owNjBzcUEKmXodSbuB/+FKJUuTynyq1uwPTjJMUTrR
            9ZT9asYrqmpIUORo8fg7Tcep+4c9S+HLWmq7WaaDDZWI9Zl5RxbAXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-10T19:58:54Z"
    mac: ENC[AES256_GCM,data:CvSWVeSvJEpycXKW82lGbfmps7D0DtRYFEHqvkUL5QFFYE63mZWFAOhgO0ilfN4TvStr+fZUNI9o5+KMYZ/EAh5FDJc0pDNHj10lohX/JhAdE5/hOFrgq4DRFxGamZrwccMk8xvpN3nmYyhpUU0xxgLxXd7o2h7eNPAwEzSAX8A=,iv:IMOcBWUgV994LYOvJNTXYVwQdxtSN5oPIXckFHMNcN8=,tag:8sB8axf0XWsR+8KnKngy5w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
