apiVersion: v1
kind: Secret
metadata:
    name: iterato-db-app
    namespace: iterato
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:iQ/PQivOlQ==,iv:2OfxBE74kn2Fabudqh/m8T7wDUsuHXj100Iq9rf5Klo=,tag:q+rX/zu0ZI+PdM6qbyctWw==,type:str]
    password: ENC[AES256_GCM,data:JwUzbxHkgzudNvQJng6IDy1iDf4vE6yTbx8l8qu2Xtk=,iv:ylXCjYE6ngm5WJa/4/0lTOITGRRmMZBOMLqoX5/Ldmk=,tag:aon42tfTRugW42sn40vDFA==,type:str]
sops:
    age:
        - recipient: age1nx88s3q0e02zhyycd9q4lwxqts9e6cenrvlxfp7ka2ghaxzwa5hqhex8h6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MFBqTENSRDFVODQ0SVB0
            aTMvTXlGeEc4cTdUZC9LZVkwMWE3UGwxT0NvClhHUEhTUVJjOEZTUmtpL2ZpcjVT
            Umtqa2pmU1Q4Y1c5dnp5dnFvdHNYR0EKLS0tIENpdzVNeTQvQStBT1RQOGg0OUR0
            dHV1V2ZCM2RaMlZFTStsZW42NklEZnMKPas754Rq/EvKrfS39PNBaQZuTcS7ZWx7
            KY3pU65YDsio3+07RkaQWAeMwOm2jllY0c5gwdZakCpvP3w2QfiSrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-10T19:58:54Z"
    mac: ENC[AES256_GCM,data:qmlMRTIdHgkidHBSNvpY4DLidijOJwWP2w1SteqVxJ8JVB+9NgiU+2ckM1v0UD/yoG/GsEHWInfPqZzcYeXUatFwWfr7XhkLJ9j/ztAE2Ag4nd5M5IGeHdW3UGElUjNSTvC60ecF+up5aSTIk7Y4Il56HfGOxt2yrwSDKZZuR8o=,iv:02rQKLshlVbcQdQUZ3I8O9hpDCMF0FW0TGAhBWhkPAo=,tag:lThHIPUNnelCd2vXhcscNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
