apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: iterato-db-monitoring
  namespace: iterato
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      postgresql: iterato-db
  podMetricsEndpoints:
    - port: metrics
