apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: iterato-db-monitoring
spec:
  selector:
    matchLabels:
      postgresql: iterato-db
  podMetricsEndpoints:
    - port: metrics
