apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: iterato-db-backup
  namespace: iterato
spec:
  schedule: "0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: iterato-db
