apiVersion: apps/v1
kind: Deployment
metadata:
  name: iterato
  namespace: iterato
  labels:
    app: iterato
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: iterato
  template:
    metadata:
      labels:
        app: iterato
    spec:
      containers:
        - name: iterato
          image: ghcr.io/hermannh34/iterato:40891b0
          ports:
            - containerPort: 3000
              protocol: TCP
          envFrom:
            - secretRef:
                name: iterato-env
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /up
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /up
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
