apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm
  namespace: openwebui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
        - name: litellm
          image: ghcr.io/berriai/litellm:main-latest
          ports:
            - containerPort: 4000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: litellm-secrets
                  key: OPENAI_API_KEY
            - name: DATABASE_URL
              value: "postgresql://user:pass@postgres:5432/fakedb"
            - name: LITELLM_MASTER_KEY
              value: "sk-1234-very-secret-key"
            - name: LITELLM_SALT_KEY
              value: "sk-very-secure-salt-key"
            - name: STORE_MODEL_IN_DB
              value: "true"

