apiVersion: v1
kind: Secret
metadata:
    name: saas-starter-env
    namespace: saas-starter
type: Opaque
stringData:
    AUTH_SECRET: ENC[AES256_GCM,data:e44hGqy13Bu8PZNosezUYDK4mwfOm6tBFVU21muut/XMIhKw1uXC+iikuSK45yonQKQEaZ9KSYz2fzYfDKlCVQ==,iv:z7HjGrTaMzLCiLanoTI6Nw6vi8u9w3GxwR5qhqBo5aA=,tag:Ct6wptwaAk1YSB6Ti3qz+g==,type:str]
    BASE_URL: ENC[AES256_GCM,data:nj46Y7gKln1SgCLb2Wga6clJYRHp05qM3/BjTx0p4j/44rt/,iv:zQ8cjjNyyJAcvwIRVSSQ/OV5Dc2aY3Zn6Z0ZcBp0YlE=,tag:NYWEhZtYAiS0YqF7lA3G1g==,type:str]
    STRIPE_SECRET_KEY: ENC[AES256_GCM,data:F4ouoAD7QO1waTSjXdAOFxQ5oA==,iv:lYhFODp6AoIzDaonUclUxgXjR4citNsafF5ui27EmB4=,tag:eNqXAMvM15G7jc/GKr7gjQ==,type:str]
    STRIPE_WEBHOOK_SECRET: ENC[AES256_GCM,data:T18S6+HJCSJT7cOoG+TZ0/0=,iv:2XxPXXNVeozJVW4WdR+s39I1S0CoL+yeq3nzMuPiyAg=,tag:ipvRbGK3lHRSZNN+VPVOFg==,type:str]
sops:
    age:
        - recipient: age1nx88s3q0e02zhyycd9q4lwxqts9e6cenrvlxfp7ka2ghaxzwa5hqhex8h6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUzZwNnFzTWR5a2kyL3Ji
            UHQrcFhxOU9JcDFIMXpYOXM5WDhaWFNxK3dzClgxOE8yYzdTbDFXeHRKL0ljS1No
            UDVicGhURXB4dUc3akt5U1M5OUFwQm8KLS0tIDJKNk5TeXJnSGdCb2cyTjRhODRz
            Z3NRbnNwZy9jZFB0UmpuTHhvb2xOcVEKbGPvDCnhvsp46sjG/AU4I5MJrqQdvia5
            QJ4S7BEH3AaPO/M4VaZE1G27ZSx9ozapbUe9kN6Ru1bq6cxP3zW7QQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T01:37:42Z"
    mac: ENC[AES256_GCM,data:jtYk4pRHeXPmYq99uLTQJDv25Sf7WPr6tpcSX3RHWcycbTUs+Cqa7oACV+s3KT4HTJJB0HVZYaxbg2C6SBmsNQt82WGen/7biEVdK4e+ik/xG3hx8SqMViWx5OE/8fFZHwDcNkuPGbs07f5oUkxiBcwHnXi2t/OxFMydz9bEwQE=,iv:jEG3vnbRS7Q5+0iYL2Iz+Jb3TnrXxYi3tWbjNSusxag=,tag:cPkmAfP+965k/IbpW0YMMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
