apiVersion: v1
kind: Secret
metadata:
    name: saas-starter-backup-s3
    namespace: saas-starter
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:c05hPWSv5R/TokRFb8g+PLnXRuqs38wOqXLEWgW/wEQ=,iv:hGMEF86Mnb4uh3sWysC4ErvtZWKpWgJnaus96E1Mg88=,tag:OiWlibq8sAiRm+oyQl4x5w==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:H6T8SE0NaKtkqI8Oe7yLuhitsT/wPKZAcsjgFnG/C2NzbIeBeJQnlhLnSpqKRKimIDUcagSVOHbtQhqqEr/xXw==,iv:zv2gg+4XXnBI5AEtHbWMXhM+XLfzs1+/sSENrCPvSPw=,tag:ezhGP8JexQ5uXROAWRoVnw==,type:str]
sops:
    age:
        - recipient: age1nx88s3q0e02zhyycd9q4lwxqts9e6cenrvlxfp7ka2ghaxzwa5hqhex8h6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcENRc3d4ZWVCZ3JFS0V1
            Y0ZUZkVBZGpVOExScS9qckZnR0FheW1lbUVNCnZzbXdla2YybU93SDlPeXZvM1lR
            TksxaVR1RUtGQTVsbFJnb0RXTUNvK1EKLS0tIG5aMTh0SU9MS1lZMmF4eVRhWTVx
            dzltd3YvUXM1bDJBS3VRdVE1Z2xkWE0KZ145L6eR+qEW0x4y/0/3mX+FYq40XBKx
            iQFTwPjCUb80vMitReY7Usl+VmbR2QxkHrsHr9nC1H/nsmKU8elWFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-14T19:07:43Z"
    mac: ENC[AES256_GCM,data:2rJ88FXaXEB2Ua0lm61WC2pTTahHegGiP7ZDnz1h0WW5c8mM0qtA2/+eolkdwACn7jKkVh3KwUCyTfmgdkqEyJQn8NH/RUySHNJ9c/c/qfDOjpsUwJ5XfkG5codV2LHncwdAPjay6fxE8qJIvCQxk74DwdOxL3PZaqVyfkb/Ql8=,iv:O621uMQRD3LjAQET+ZoC/vhC8t3a+p4jA/cLqGYF3Ls=,tag:ZSVL4Ku/wAv2lsuwtZ7Z0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
