apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: saas-starter-db-backup
  namespace: saas-starter
spec:
  schedule: "0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: saas-starter-db
