apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secrets
    namespace: forgejo
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:eQMhfV+o4/B7BrQk3mUUntHJXiGBNnMDKFX7v0pEYnk=,iv:hxn9JiUzDPuaL0hKfdK6B/pQ70MvV1YsOiJml8nbE3I=,tag:uWAekHS95cDG2k1o9/HWAw==,type:str]
    jwtSecret: ENC[AES256_GCM,data:/9SUcNw4GirLw9Ag3ZslDteoB6+crY1WbDSFlq/837zIH23nkemWPN4BeE1lZkfrhNjmMPyfqOsjOI5bWFWt2w==,iv:X5gyU6Krj3CvpvS4heC9VHt9wcew4p0vvJ8WE8WIUNk=,tag:KkWmhUeUWE+wqzI4sVCvFg==,type:str]
sops:
    age:
        - recipient: age1nx88s3q0e02zhyycd9q4lwxqts9e6cenrvlxfp7ka2ghaxzwa5hqhex8h6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcHBweU4vZDJuVk5VZXNp
            MkVZZ2hBMUZCdDRzOXNxTVc2ZDdHbFJZL0RFCmpxV1ljN2crTU0vSGtCUG5DMEY0
            SGtaMmNCYmxLdHcrWnVSQkhLL2lQSVkKLS0tIDhxMC9BUDRzQXdyQm9Cblo4b05y
            Smw2a3VLU0hqY2lOcUpxM1RoeERZNFEKutq8lK5YSBth3++qJ9yyTU1LFpAN6SQE
            Fw39QSf9k4/r/TFjrW+lCeO8GocOdhkTLvJZvznfR4N2YR8dNBxqLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T00:48:58Z"
    mac: ENC[AES256_GCM,data:Vrqxg/YgBsVqHznLYAebCWFWLdLLtFm34qURWGyC7h3rU4kusgrsnzKK3zmwYOv1CZnstueuVhyL/sgAgAKRkD63c8Kwn0YDrrj3keABbhp4JDgOj82TD2myB3H/XFCLMbtfAWiF3qUNit7SLzUtkz2lkPT5GTb3zijGvOcrk8o=,iv:xpLeoPH0ei6co2ZhcaOppCk4jAf+MAX2DhjK77BVt9E=,tag:ElkLluuoaWZ1K6u1toIQ2w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
