apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
    namespace: forgejo
type: Opaque
stringData:
    runnerToken: ENC[AES256_GCM,data:5sH5Rz/BFLaP7YH7mqSXhjVY8lgaxVGfMBiSHmSw0EZ/TaNpLetySvohn7IkXM+pudul6q0mvk4ubCmzrt8S1Q==,iv:tvhe9yCGJhuK5moAfHaa05JsfcPt8duYmBtiJZOZK/w=,tag:8DzefWDBpQ5dJHNejP+O8Q==,type:str]
sops:
    age:
        - recipient: age1nx88s3q0e02zhyycd9q4lwxqts9e6cenrvlxfp7ka2ghaxzwa5hqhex8h6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TE9aYlB1NHRlZEZKMzJi
            a1AzT3ZNU0gzTzEyWE56OHZQcWhJZ0VvY3dRClR4Wmh3QUNtSUI0eGtXeVJjblNC
            MVlBOHpNZHlJTUtOUVBjcTREdXMxeGMKLS0tIFAwc2lpYnNSSTkxUk9BendxT2hH
            U3M2SVdPcWg5Mml5QkhreGFLUEhIazQKiprfWbPirDYKpGtAvjFGQS8rkT/+AU+A
            H2Ik9YAjAAkb4cVnJ6b1QZItE5vMULHpDBqy9+Y4aN9fg6zYJdCUjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T00:48:58Z"
    mac: ENC[AES256_GCM,data:o1ILqDCi6ZdGw746GgSiY2fDUE/yjEBuK5h3OgCpUafBk8LsNYhMRyYzLgHWwb5tGLcfgD8elC3sOsXUiiCcFRKY1rIB/fBDQQ89sLnZcIE+WZ2VkXC9slialjnTV4hWk0B3D1BD+u9rZJ72/HjAdPOK37k/oXxt6syhYGVnwbk=,iv:HKck29qG0nbmGP2zI9Wkd4MglLM1kG4jMuMzTKj3McU=,tag:R+kOwSPVD4v2bzI6NNkf6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
