apiVersion: v1
kind: ConfigMap
metadata:
    name: linkding-env
    namespace: linkding
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:zvQlUxFL9qLL6YQB1Q==,iv:K26RogNpPU1ed4yfppdW++M2TbySxZ50jOog5J1ngGY=,tag:ckq8XBZN9WFmVpBa5f9jrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfmusxgxpv8292s3d2x60lemqscsff7zcsnfxd67nk348pzlgs3qth3q8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBOFhBeWtuY3lFL3ZyTUd0
            RncvQmJtWE5tL1FUV1ZlMTdKdksvUGUvaGlJCmc4MlR3czkvQUMzRXd0bDY2L2NW
            QWVmeEM5b0U0bWxXdE52TUM0NUhZaTAKLS0tIEd5ZEt6MEY4NmRzYzJ4NEpCYmY0
            ZERrMTVUUE1iK3RmQUxpeUpXTnUwTU0KwOnyH9kAOQQWjBcWlnzudrS5PqYFjYyq
            usu4GJvzMfwh+BXJQh5wqvMOFVM6xau0a+YizqHrSOLvKJMJUzhL4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-10T21:42:22Z"
    mac: ENC[AES256_GCM,data:1BiUKZWuooQk618yAcUf9tJEyu4HgoVGdOFSUJZxja4BNRv7xZo+RAp/YVDyMMLAI/Yr3eHwCziyBvQ79iLrHskRHmMCeouQ/imyw+3/1t1krBDyvyGxRC1b5leEIlmVJye+qm50GqGUUw6v5VoywEqUdOw5DUR/q6vRVi7SAyU=,iv:etwMh0Kc/CH6Nw/JPW4hV6a9fBqKOuO69Fxkh/qmMYA=,tag:WxNJeJxglDwhiIQQqtlVqw==,type:str]
    pgp: []
    encrypted_regex: ^(LD_SUPERUSER_NAME|LD_SUPERUSER_PASSWORD)$
    version: 3.8.1
