apiVersion: v1
kind: Secret
metadata:
    name: linkding-env
    namespace: linkding
type: Opaque
stringData:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:CzE1THuV4BFGw1CI6Q==,iv:zq1gf5JrEEZ/w52CMjC5OlSUk0IwpwVs9CuS5LtyN1w=,tag:6XWpLFRYO/7xz7QtLCV9BA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:Z0I83ibt,iv:pqEHBlXWZHT+qmSw/Heb8Zxk+n+IE69jRzU/O53CI3c=,tag:DkddLEl5jNFa0LC/Zs5tGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pfmusxgxpv8292s3d2x60lemqscsff7zcsnfxd67nk348pzlgs3qth3q8s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOU5PVzQ1eHV1OTI3OVZW
            ZUozK0gyUXk0NjVna05KRjcyWUkwUi82TW0wCjExRU1EVDh6YnQ4NlFweDNMUjFK
            UGIyUEdWRUJIY2Rqc05LektkQlFyYkUKLS0tIFJwZVRpK0ZONnJQbmN6Y25RSlRN
            WThBVnUydHF4bzRERnlvazJ1ekZSMUkKisB4QOBVpypXPpMZZoxElhFhb+jp+VhA
            iHljghXpnThW/pccWLzMUtH8W4VIx5I1i5Ovo0O3iU+HYOSepsyGVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-10T22:18:57Z"
    mac: ENC[AES256_GCM,data:x8Md2vnYhN0Zj+f4Gh7hnsuY1I02j0gIyMhnEOwHjTV8YdMy4gpTQn4du8nGJmpSLrhOoGSmx1awtwHto/T5K4JGLBIsy6S5hioEAdjazdi+alOikkP7lO60plHyEq1p9EcXKzq6Rfq453NhvtcrbBse2kO76/kTIK7iWJsL2v4=,iv:D1+DX2vHPpeYCSQteGY612KtjVoetOst4KOxAa501zg=,tag:OFmQkSAvi1VePL2xO4oaQw==,type:str]
    pgp: []
    encrypted_regex: ^(LD_SUPERUSER_NAME|LD_SUPERUSER_PASSWORD)$
    version: 3.8.1
