apiVersion: v1
kind: Service
metadata:
  name: beszel-hub
  namespace: beszel
  labels:
    app: beszel-hub
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8090
      targetPort: 8090
      protocol: TCP
  selector:
    app: beszel-hub